#!/usr/bin/bash

BASEDIR=/srv/hackgrab
INTERVAL=10

cd ${BASEDIR}/content

#Start by flagging each active channel to be iterated over.
for TORUN in */url
do
    FOLDER=`dirname "${TORUN}"`
    touch "${FOLDER}/.ag_do"
done

while [ `ls */.ag_do 2>/dev/null | wc -l` != 0 ]
do
    TORUN=`ls -tr */url | head -n1`
    FOLDER=`dirname "${TORUN}"`
    echo "Calling launch on ${FOLDER}"
    ${BASEDIR}/bin/launch "${FOLDER}"
    sleep ${INTERVAL}
done

