#!/bin/bash

#Flatten the structure
mv ????/??/??/*.mp4 . 

#Remove the dated dirs
rmdir ????/??/?? ????/?? ????

#Loop over all of the files
for i in *.mp4
do
    #Extract the date
    echo ${i}
    DATE=`/usr/bin/mediainfo "${i}" | grep "Tagged date" | head -n1 | cut -f2 -d":"`

    #If there is one, use it to set the file's timestamp.
    if [ "${DATE}" ]
    then
	touch --date="${DATE}" "${i}"
    fi
done

#Call datesort
../datesort.py
