#!/bin/bash

BASEDIR=/srv/hackgrab

BINDIR="${BASEDIR}/bin"
DATADIR="${BASEDIR}/content"

MESSAGE=""

#First, determine what we're talking about
if [ "${1}" ]
then
    TARGET="${1}"
else
    DIR=`pwd`
    TARGET="`basename "${DIR}"`"
fi

echo "Target is ${TARGET}"

#Make sure it exists
cd "${DATADIR}/${1}" || MESSAGE="Unable to find ${1}."

echo 1

#If so, and it's disabled, re-enable it.
if [ -e url_hold ]
then
    mv url_hold url
fi

echo 2

#If there's no error messages so far, then plough forward
if [ "${MESSAGE}" = "" ]
then
    ${BINDIR}/launch "${TARGET}"
else
    echo "${MESSAGE}"
fi

