#!/bin/bash

SERVERLIST='Hackgrab-a Hackgrab-b Hackgrab-c Hackgrab-d'
THIS='/srv/hackgrab/bin/launch'

HOSTNAME=`hostname`

ARRAY=(${SERVERLIST})
SIZE=${#ARRAY[@]}
INDEX=$(($RANDOM % $SIZE))
SERVER=${ARRAY[$INDEX]}

if echo ${SERVERLIST} | grep -qw "${HOSTNAME}"
then
    /srv/hackgrab/bin/grab_one >> /srv/hackgrab/logs/log 2>&1 &
else
    ssh ${SERVER} ${THIS}
fi

