#!/bin/bash

SERVERLIST='Hackgrab-a Hackgrab-b Hackgrab-c Hackgrab-d'
BASE='/srv/hackgrab'

THIS="${BASE}/bin/launch"
RETRIES=5
INTERVAL=10

HOSTNAME=`hostname`
LOG="${BASE}/logs/${HOSTNAME}.log"

ARRAY=(${SERVERLIST})
SIZE=${#ARRAY[@]}


if echo ${SERVERLIST} | grep -qw "${HOSTNAME}"
then
    if [ -e /dev/shm/Hackgrab_PID ]
    then
	OLDPID=`cat /dev/shm/Hackgrab_PID`
	if ps -p ${OLDPID}
	then
            exit 2
	fi
    else
	/srv/hackgrab/bin/grab_one >> ${LOG} 2>&1 &
    fi
else
    RETRY=true
    while ${RETRY}
    do
	  INDEX=$(($RANDOM % $SIZE))
	  SERVER=${ARRAY[$INDEX]}
	  echo "Launching on ${SERVER}"
	  ssh ${SERVER} ${THIS}
	  if [ $? != 2 ]
	  then
	      RETRY=false
	  else
	      RETRIES=$((${RETRIES} - 1))
	      if [ ${RETRIES} = 0 ]
	      then
		  echo "Out of retries.  Exiting."
		  RETRY=false
	      else
		  echo "${SERVER} is busy.  Trying again in ${INTERVAL} seconds."
		  sleep ${INTERVAL}
	      fi
	  fi
    done
fi

