#!/bin/bash

BASEDIR=/srv/hackgrab

cd ${BASEDIR}
echo "Node status:"
for i in metadata/status_*
do
    node=`echo ${i} | sed -e "s/^metadata\/status_//"`
    status=`cat ${i}`
    printf "    %-12s: %s\n" ${node} "${status}"
done
echo

echo "Filesystem status:"
echo -n "    "
df -h . | tail -n1
echo


cd ${BASEDIR}/content

echo "Channel counts:"
printf "    %-12s: %s\n" "Active" `ls */url | wc -l`
printf "    %-12s: %s\n" "Disabled" `ls */url_hold | wc -l`

echo

echo "Next ten downloads:"
ls -ltr */url | head -n10 | cut -d' ' -f 6- | while read i
do
    printf "    %s\n" "`echo "${i}" | sed -e "s/\/url//"`"
done

